### ISSUE TITLE
PSK -> .pem Files?

### ISSUE THREAD

**Issue by msolters** [Rantanen/node-dtls#15]
Hi, and thank you for this DTLS server.  It's the first I've tried that more or less works out of the box!

Context: I have some embedded devices acting as both CoAP servers and clients.

By default, enabling DTLS on these devices uses a pre-shared key phrase as the basis of the cipher.

How would I go about creating the `.pem` files for this module based on a known PSK string?

**Comment by Rantanen** [comment]
I have no idea. I'm not all that familiar with the different certificate formats unfortunately.

Also as a warning: This DTLS server is far from complete as the current state in the readme indicates. It does implement the basics of DTLS but many ciphers, extensions, etc. are missing as is renegotiation and message validation (validation as in handling error messages gracefully and returning alerts as per the spec instead of just ignoring these).

**Comment by msolters** [comment]
Ok, thanks!
