### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by nickdesaulniers** [Rantanen/node-dtls#9]
high there, I don't see your module listed on npmjs.org, is it not published?
https://www.npmjs.com/search?q=node-dtls

**Comment by Rantanen** [comment]
It's far from stable at the moment and as such I can't give any guarantees to it working. Especially since it's a security-related project, I don't want people finding it on npmjs and assuming it works without realizing how much of a work-in-progress it is.

If you want to use it with npm, you should be able to use it with: `npm install https://github.com/Rantanen/node-dtls/tarball/master`.
